### ISSUE TITLE
qbauto_copy.log里为啥没有详细的上传速度和进度了？

### ISSUE THREAD

**Issue by kaiant924** [666wcy/qbittorent_rclone_upload#5]
大佬，为啥qbauto_copy.log里的详细上传速度功能删除了吗？我想看上传速度但是日志里找不到

**Comment by kaiant924** [comment]
> 大佬，为啥qbauto_copy.log里的详细上传速度功能删除了吗？我想看上传速度但是日志里找不到

就是rclone的上传日志，里面详细的上传速度时间等参数的那种。

**Comment by 666wcy** [comment]
未曾有过变动，请检查自己的操作
此项目过久，目前主要维护的是[此文](https://weinb.top/index.php/archives/164/)中的QB端

**Comment by kaiant924** [comment]
日志中只有qb.log中写入了rclone上传的信息，如下：
bash /upload/qb_auto.sh  MomsTeach.21.09.08.Jamie.Michelle.Maya.Woulfe.Hand.Caught.In.The.Cookie.Jar.XXX.480p.MP4-XXX /home/kaiant/torrents/qbittorrent/MomsTeach.21.09.08.Jamie.Michelle.Maya.Woulfe.Hand.Caught.In.The.Cookie.Jar.XXX.480p.MP4-XXX/mts.21.09.08.jamie.michelle.maya.woulfe.hand.caught.in.the.cookie.jar.mp4 /home/kaiant/torrents/qbittorrent/MomsTeach.21.09.08.Jamie.Michelle.Maya.Woulfe.Hand.Caught.In.The.Cookie.Jar.XXX.480p.MP4-XXX /home/kaiant/torrents/qbittorrent/ 1 258632618 a7b351359ca42aca24191badc6b44377530a689e
[2021-09-10 14:22:48] 类型：文件
09/10 14:22:48 [INFO] Start upload files...
[2021-09-10 14:30:59] 不自动删除已上传种子
种子名称：MomsTeach21.09.08.Jamie.Michelle.Maya.Woulfe.Hand.Caught.In.The.Cookie.Jar.XXX.480p.MP4-XXX
内容路径：/home/kaiant/torrents/qbittorrent/MomsTeach.21.09.08.Jamie.Michelle.Maya.Woulfe.Hand.Caught.In.The.Cookie.Jar.XXX.480p.MP4-XXX/mts.21.09.08.jamie.michelle.maya.woulfe.hand.caught.in.the.cookie.jar.mp4
根目录：/home/kaiant/torrents/qbittorrent/MomsTeach.21.09.08.Jamie.Michelle.Maya.Woulfe.Hand.Caught.In.The.Cookie.Jar.XXX.480p.MP4-XXX
保存路径：/home/kaiant/torrents/qbittorrent/
文件数：1
文件大小：258632618Bytes
HASH:a7b351359ca42aca24191badc6b44377530a689e
上传地址:gdriveqb:/kai/MomsTeach.21.09.08.Jamie.Michelle.Maya.Woulfe.Hand.Caught.In.The.Cookie.Jar.XXX.480p.MP4-XXX
-------------------------------------------------------------
但是缺少详细的上传速度数据呀。

**Comment by kaiant924** [comment]
> 未曾有过变动，请检查自己的操作
> 此项目过久，目前主要维护的是[此文](https://weinb.top/index.php/archives/164/)中的QB端

[https://raw.githubusercontent.com/666wcy/qbittorent_rclone_upload/main/log.png](url)
就是像您项目下面的图片展示中的qbauto.log下显示的那样。

**Comment by kaiant924** [comment]
> 未曾有过变动，请检查自己的操作
> 此项目过久，目前主要维护的是[此文](https://weinb.top/index.php/archives/164/)中的QB端

大佬您看下是不是这个上传的函数在执行rclone copy -v "${UPLOAD_PATH}" "${REMOTE_PATH}"之后没有将对应的信息写入日志啊？



function UPLOAD_FILE() {
    echo -e "$(DATE_TIME) ${INFO} Start upload files..."
    echo -e "$(DATE_TIME) ${INFO} Start upload files..." >> ${log_dir}/qb.log
    RETRY=0
    while [ ${RETRY} -le ${RETRY_NUM} ]; do
        [ ${RETRY} != 0 ] && (
            echo
            echo -e "$(DATE_TIME) ${ERROR} Upload failed! Retry ${RETRY}/${RETRY_NUM} ..."
            echo -e "$(DATE_TIME) ${ERROR} Upload failed! Retry ${RETRY}/${RETRY_NUM} ..."  >> ${log_dir}/qb.log
            echo
        )
        echo ${UPLOAD_PATH}
        echo ${REMOTE_PATH}
       rclone copy -v "${UPLOAD_PATH}" "${REMOTE_PATH}"
        RCLONE_EXIT_CODE=$?
        if [ ${RCLONE_EXIT_CODE} -eq 0 ]; then
            
            break
        else
            RETRY=$((${RETRY} + 1))
            [ ${RETRY} -gt ${RETRY_NUM} ] && (
                echo "$(DATE_TIME) ${ERROR} Upload failed: ${UPLOAD_PATH}" 
                echo "$(DATE_TIME) ${ERROR} Upload failed: ${UPLOAD_PATH}"  >> ${log_dir}/qb.log
               
            )
            sleep 3
        fi
    done
}

**Comment by kaiant924** [comment]
问题解决了。
在rclone的复制指令后添加 --log-file ${log_dir}/qbauto_copy.log就可以把rclone复制时的info  error等信息写入日志里了。
